language: generic 
sudo: required
sevices:
    - docker

before_install: 
    - docker build  -t toha70/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true toha70/docker-react npm run test
